async function DataDownload() {
  const userId = window.localStorage.getItem("user_id");
  const token = window.localStorage.getItem("access_token");
  try {
    const data = await fetch(
      `https://jusanhr.herokuapp.com/form/download/info/${userId}`,
      {
        method: "GET",
        headers: {
          "Content-Type": "application/json",
          Authorization: "Bearer_" + token,
          // // 'Content-Type': 'application/x-www-form-urlencoded',
        },
      }
    );
    const dataJson = await data.json();
    console.log(dataJson);
    return dataJson;

    // return {
    //   iin: "string",
    //   oldSurname: "string",
    //   dateOfBirthday: "string",
    //   placeOfBirth: "string",
    //   nationality: "string",
    //   citizenship: "string",
    //   documentSeries: "string",
    //   documentNumber: "string",
    //   documentIssued: "string",
    //   homePhoneNumber: "string",
    //   workPhoneNumber: "string",
    //   mobilePhoneNumber: "string",
    //   contactPersonFio: "string",
    //   contactPersonDegreeOfRelationship: "string",
    //   contactPersonPhoneNumber: "string",
    //   email: "string",
    //   permanentRegistrationAddressCity: "string",
    //   permanentRegistrationAddressDistrict: "string",
    //   permanentRegistrationAddressRegion: "string",
    //   permanentRegistrationAddressStreet: "string",
    //   permanentRegistrationAddressHouseNumber: "string",
    //   permanentRegistrationAddressCorpus: "string",
    //   permanentRegistrationAddressApartment: "string",
    //   actualAddressCity: "string",
    //   actualAddressDistrict: "string",
    //   actualAddressRegion: "string",
    //   actualAddressStreet: "string",
    //   actualAddressHouseNumber: "string",
    //   actualAddressCorpus: "string",
    //   actualAddressApartment: "nurasyl",
    //   universityInfoDtos: [
    //     {
    //       startDateOfEducation: "string",
    //       endDateOfEducation: "string",
    //       nameOfInstitution: "string",
    //       speciality: "string",
    //       formOfStudy: "string",
    //       qualification: "string",
    //     },
    //     {
    //       startDateOfEducation: "string",
    //       endDateOfEducation: "string",
    //       nameOfInstitution: "string",
    //       speciality: "string",
    //       formOfStudy: "string",
    //       qualification: "string",
    //     },
    //   ],
    //   additionalEducationInfoDtos: [
    //     {
    //       yearOfGraduation: "string",
    //       durationOfTraining: "string",
    //       nameOfCourse: "string",
    //       speciality: "string",
    //       academicDegreeOrCertificates: "string",
    //     },
    //     {
    //       yearOfGraduation: "string",
    //       durationOfTraining: "string",
    //       nameOfCourse: "string",
    //       speciality: "string",
    //       academicDegreeOrCertificates: "string",
    //     },
    //   ],
    //   startOfWorkingOne: "string",
    //   endOfWorkingOne: "string",
    //   workingPlaceInfoOne: "string",
    //   workTypeOne: "string",
    //   workingPlaceAddressOne: "string",
    //   workingPlacePhoneNumberOne: "string",
    //   positionOne: "string",
    //   managerFullNameOne: "string",
    //   managerPhoneNumberOne: "string",
    //   reasonForDismissalOne: "string",
    //   startOfWorkingTwo: "string",
    //   endOfWorkingTwo: "string",
    //   workingPlaceInfoTwo: "string",
    //   workTypeTwo: "string",
    //   workingPlaceAddressTwo: "string",
    //   workingPlacePhoneNumberTwo: "string",
    //   positionTwo: "string",
    //   managerFullNameTwo: "string",
    //   managerPhoneNumberTwo: "string",
    //   reasonForDismissalTwo: "string",
    //   startOfWorkingThree: "string",
    //   endOfWorkingThree: "string",
    //   workingPlaceNameThree: "string",
    //   workTypeThree: "string",
    //   workingPlaceAddressThree: "string",
    //   workingPlacePhoneNumberThree: "string",
    //   positionThree: "string",
    //   managerFullNameThree: "string",
    //   managerPhoneNumberThree: "string",
    //   reasonForDismissalThree: "string",
    //   profRefFullName1: "string",
    //   profRefWorkPlace1: "string",
    //   profRefWorkPosition1: "string",
    //   profRefTel1: "string",
    //   profRefFullName2: "string",
    //   profRefWorkPlace2: "string",
    //   profRefWorkPosition2: "string",
    //   profRefTel2: "string",
    //   profRefFullName3: "string",
    //   profRefWorkPlace3: "string",
    //   profRefWorkPosition3: "string",
    //   profRefTel3: "string",
    //   maritalStatus: "string",
    //   spouseFIO: "string",
    //   spouseDateOfBirthday: "string",
    //   spouseWorkingInfo: "string",
    //   spouseWorkingPosition: "string",
    //   spouseAddress: "string",
    //   spouseCitizenship: "string",
    //   spouseContacts: "string",
    //   childrenInfoDtos: [
    //     {
    //       dateOfBirthday: "string",
    //       phoneNumber: "string",
    //       workPlace: "string",
    //       fio: "string",
    //     },
    //     {
    //       dateOfBirthday: "string",
    //       phoneNumber: "string",
    //       workPlace: "string",
    //       fio: "string",
    //     },
    //   ],
    //   relativesInfoDtos: [
    //     {
    //       degreeOfRelationship: "string",
    //       dateOfBirthday: "string",
    //       workingPlace: "string",
    //       workingPosition: "string",
    //       address: "string",
    //       phoneNumber: "string",
    //       fio: "string",
    //     },
    //     {
    //       degreeOfRelationship: "string",
    //       dateOfBirthday: "string",
    //       workingPlace: "string",
    //       workingPosition: "string",
    //       address: "string",
    //       phoneNumber: "string",
    //       fio: "string",
    //     },
    //   ],
    //   additionalWorkingInfoDtos: [
    //     {
    //       name: "string",
    //       inn: "string",
    //       address: "string",
    //       typeOfWork: "string",
    //       phoneNumber: "string",
    //     },
    //     {
    //       name: "string",
    //       inn: "string",
    //       address: "string",
    //       typeOfWork: "string",
    //       phoneNumber: "string",
    //     },
    //   ],
    //   relativesInJusanDtos: [
    //     {
    //       degreeOfRelationship: "string",
    //       departmentAndPosition: "string",
    //       fio: "string",
    //     },
    //     {
    //       degreeOfRelationship: "string",
    //       departmentAndPosition: "string",
    //       fio: "string",
    //     },
    //   ],
    //   carModel: "string",
    //   carYearOfManufacture: "string",
    //   carNumber: "string",
    //   militaryStatus: "string",
    //   benefitsStatus: "string",
    //   overdueLoanStatus: "string",
    //   overdueLoanReason: "string",
    //   criminalLiabilityStatus: "string",
    //   criminalLiabilityReason: "string",
    //   relativesCriminalCaseStatus: "string",
    //   relativesCriminalCaseReason: "string",
    //   criminalCaseStatus: "string",
    //   criminalCaseReason: "string",
    //   alimonyStatus: "string",
    //   alimonyReason: "string",
    //   administrativeLiabilityStatus: "string",
    //   administrativeLiabilityReason: "string",
    //   additionalInformation: "string",
    //   additionalIncome: "string",
    //   dateOfFillingIn: "string",
    //   fio: "string",
    // };

    // return {
    //   // ...dataJson,
    //   iin: "blah",
    //   additionalEducationInfoDtos: [
    //     { yearOfGraduation: "2020-10-10", durationOfTraining: "2016-10-10" },
    //     { yearOfGraduation: "2020-10-10", durationOfTraining: "2016-10-10" },
    //   ],
    //   universityInfoDtos: [],
    // };
  } catch (error) {
    console.error("Error:", error);
  }
}

export default DataDownload;
